trigger:
- main

pool:
  name: default

jobs:
- job: run_dast_scan
  displayName: Run DAST Scan
  steps:
  - task: Docker@2
    inputs:
      command: login
      containerRegistry: 'dockerhub' 
      azureSubscriptionEndpoint: 'MyDockerServiceConnection'

  - task: Bash@3
    displayName: 'Run OWASP ZAP Scan'
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p owaspzap
        docker run --rm -v $(pwd)/owaspzap:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://172.213.198.195 -J zap_report.json -r zap_report.html -w zap_report.txt

  - task: Bash@3
    displayName: 'Ensure report.txt exists'
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p owaspzap
        if [ ! -f owaspzap/zap_report.txt ]; then
          touch owaspzap/zap_report.txt
        fi

  - task: CopyFiles@2
    condition: succeededOrFailed()
    inputs:
      SourceFolder: 'owaspzap/'
      TargetFolder: '$(Pipeline.Workspace)'

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: '$(Pipeline.Workspace)/zap_report.txt'
      artifact: 'owasp_zap_report'
      publishLocation: 'pipeline'
    displayName: 'Publish ZAP Report'
