pr: none # Pour les tests manuels seulement

pool:
  name: default  # Assurez-vous que l'image de l'agent supporte JDK 17 et Maven

stages:
  - stage: build_and_dockerize
    displayName: 'Build and Dockerize Spring Boot Application'
    jobs:
      - job: build_and_dockerize
        displayName: 'Build and Dockerize Application'
        steps:
          - checkout: self

          # Step 1: Vérifier l'installation de JDK 17
          - script: 
              java -version
              javac -version  # Assurez-vous que le compilateur javac est également disponible
            displayName: 'Verify JDK 17 Installation'


          # Step 3: Build Docker image
          - script: |
              docker build -t brahmieya/stageback:$(Build.BuildId) .
            displayName: 'Build Docker Image'# Step 4: Push Docker image to Docker Hub
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerhub'  # Remplacez par le nom de votre connexion de service Docker Hub
              repository: 'brahmieya/stageback'  # Remplacez par le nom de votre repository Docker Hub
              command: 'push'
              tags: 'brahmieya/stageback:$(Build.BuildId)' 
                