trigger:
- main

pool:
  name: default

jobs:
- job: run_dast_scan
  displayName: Run DAST Scan
  steps:
  - task: Docker@2
    inputs:
      command: login
      containerRegistry: 'dockerhub' 
      azureSubscriptionEndpoint: 'MyDockerServiceConnection'

  - task: owaspzap@1
    inputs:
      scantype: 'targetedScan'
      url: 'http://172.213.198.195' # replace with your staging URL here
      dockerImage: 'zaproxy/zap-stable:sha256-f88599eb7fd9a04164f011f3a8a6f01f800f1fb72f1a464831e7148322810311.att0' # Specify the known available version
    displayName: 'OWASP ZAP Scan'
  
  - task: CopyFiles@2
    condition: succeededOrFailed()
    inputs:
      SourceFolder: 'owaspzap/'
      TargetFolder: '$(Pipeline.Workspace)'
  
  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: '$(Pipeline.Workspace)/report.json'
      artifact: 'owasp_zap_report'
      publishLocation: 'pipeline'
    displayName: 'Publish ZAP Report'
