trigger:
- main

pool:
  name: default

jobs:
- job: run_dast_scan
  displayName: Run DAST Scan
  steps:
  - task: Docker@2
    inputs:
      command: login
      containerRegistry: 'dockerhub' 
      azureSubscriptionEndpoint: 'MyDockerServiceConnection'

  - task: owaspzap@1
    inputs:
      scantype: 'targetedScan'
      url: 'http://172.213.198.195' # replace with your staging URL here
      dockerImage: 'ghcr.io/zaproxy/zaproxy:stable' # Specify the known available version
    displayName: 'OWASP ZAP Scan'
  
  - task: Bash@3
    displayName: 'Ensure report.json exists'
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p owaspzap
        touch owaspzap/report.json

  - task: CopyFiles@2
    condition: succeededOrFailed()
    inputs:
      SourceFolder: 'owaspzap/'
      TargetFolder: '$(Pipeline.Workspace)'
  
  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: '$(Pipeline.Workspace)/s/owaspzap/report.json'
      artifact: 'owasp_zap_report'
      publishLocation: 'pipeline'
    displayName: 'Publish ZAP Report'
