apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-application
  template:
    metadata:
      labels:
        app: spring-application
    spec:
      containers:
        - name: spring-application
          image: brahmieya/stageback:$(Build.BuildId)
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/virtiversefinal?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""